In [1]:
# Q1: import numpy and pandas
import numpy as np
import pandas as pd


# Q2: Set options in pandas so it displays 30 `max_rows` 
#                                 no limit on `max_columns`
#                                 precision is 3

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)
pd.set_option('display.precision', 3)

# Q3: assign the versions of pandas and numpy to variables below
pd_version = pd.__version__
np_version = np.__version__


# Q4: Read in the csv file "olive.csv" with pandas. 
#     The filename is stored in the variable `olive_path`
#     Assign it to variable `df`

# download the data and name the columns


df = pd.read_csv(
    'http://s3.amazonaws.com/istreet-assets/cqj0wXOp6sICdTRWc5X2cw/olive.csv.txt')



# Q5: How many rows and columns are there in `df`? Put your answer in a variable `df_shape`.
df_shape = df.shape


# Q6: assign the first 2 rows of `df` to `df_first_two`
df_first_two = df[0:2]


# Q7: How many distinct data types are there in `df`?
df_data_types_count = len(df.dtypes.unique())  # this should be an integer


# Q8: In `df`, create a new column 'sub_region_raw', which will be a copy of the column 'Unnamed: 0'

df=df.assign(sub_region_raw=df['Unnamed: 0'])



# Q9: In `df`, rename 'Unnamed: 0' to 'sub_region_desc'
df.rename(columns={'Unnamed: 0': 'sub_region_desc'}, inplace=True)



# Q10: In `df`, rename the column 'area' to: 'sub_region'
df.rename(columns={'area': 'sub_region'}, inplace=True)


# Q11: In `df`, get the unique values of the field 'region'
region_unique = df['region'].unique()




# Q12: In `df`, how many unique values of the field 'sub_region' are there?
sub_region_unique_count = len(df['sub_region'].unique())  # should be an integer



# Q13: Lets take a look at the field `sub_region_desc`:

# >>> df['sub_region_desc'].head(5)
# 0    1.North-Apulia
# 1    2.North-Apulia
# 2    3.North-Apulia
# 3    4.North-Apulia
# 4    5.North-Apulia

import re
# Looks like 'sub_region_desc' has line numbers attached to the beginning of region name. Remove those and get the unique values in that field, assign it to `srd_unique`
remnumlist=[]
for i in df['sub_region_desc']:
    remnumlist.append(re.sub('\d|\.','',i))
    

df['sub_region_desc']=remnumlist


srd_unique = df['sub_region_desc'].unique()


In [90]:
A=np.array([[1,-1],[1,0]])
A*A*A*A

array([[1, 1],
       [1, 0]])

In [92]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work



In [96]:
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A':A.shape ,
    'B':B.shape ,
    'C':C.shape ,
    'D':D.shape ,
    'u':u.shape ,
    'v':v.shape 
}
dimensions

{'A': (2, 3), 'B': (2, 2), 'C': (3, 2), 'D': (2, 3), 'u': (4,), 'v': (4,)}

In [104]:
alpha = 6

u_plus_v = u+v            # u+v
u_minus_v = u-v         # u-v
alpha_times_u =  alpha*u      # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)            # u . v
norm_u =    np.linalg.norm(u)           # ||u|| 


u_plus_v            # u+v
u_minus_v          # u-v
alpha_times_u         # alpha * u, alpha = 6
u_dot_v             # u . v
norm_u               # ||u|| 

8.602325267042627

In [158]:
# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

def plus(a,b):
    try:
        return a+b
    except ValueError:
        return None
    
def dot(a,b):
    try:
        return np.dot(a,b)
    except ValueError:
        return None

A_plus_C = plus(A,D)  # A + C
A_minus_Ctranspose = A-np.transpose(C)   # A - C.T
Ctranspose_plus_3D = np.transpose(C)+(3*D)   # C.T + 3*D
B_times_A = dot(B,A)       # B*A
B_times_Atranspose = dot(B,np.transpose(A))   # B*A.T

A_plus_C               # A + C
A_minus_Ctranspose     # A - C.T
Ctranspose_plus_3D     # C.T + 3*D
B_times_A              # B*A
#B_times_Atranspose     # B*A.T

array([[-1, -5, -1],
       [ 2,  7,  4]])

In [208]:
# Q4: (bonus)

def dotexp(a,exp):
    x=a
    exp-=1 #shift exponent down, so input exp=3 counts as exp=2, which when used as range loops 3 time
    if exp==0:
        return a
    else:
        for i in range(exp):
            x=dot(x,a)
        return x

B_times_C = dot(B,C)            # B*C
C_times_B = dot(C,B)            # C*B
B_exp_4 = dotexp(B,4)              # B^4
A_times_Atranspose = dot(A,np.transpose(A))  # A*A.T np.linalg.matrix_power(B,4)
Dtranspose_times_D = dot(np.transpose(D),D)   # D.T*D

# Q4: (bonus)

B_times_C              # B*C
C_times_B              # C*B
B_exp_4                # B^4
#A_times_Atranspose     # A*A.T
#Dtranspose_times_D     # D.T*D

array([[ 1, -4],
       [ 0,  1]])